language: node_js
branches:
  only:
    - master
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
  - 10
  - 12
  - 13
script:
  - npm run build && npm run test:prod
after_success:
  - npm run coverage
  - npm run semantic-release
