name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 13]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run test suite
        run: npm run test:prod
        env:
          CI: true

      - name: On success
        run: npm run coverage
        env:
          CI: true
        run: npm run semantic-release
        env:
          CI: true
